### PR TITLE
Support prefix for Camel namespace uri with xml dsl

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by lhein** [comment]
rebase required

**Comment by lhein** [comment]
rebased

**Comment by tsedmik** [comment]
related to #74

**Comment by apupier** [comment]
I think we will need to make the Parser stateful one day to better handle the prefix stuff (unless Camel implements the support of namespace in their parser).
I'm not sure if I should do it in this PR or delay to another one.

**Pull request merged**
