### PR TITLE
FUSETOOLS2-72 - support additional components

### PR DESCRIPTION
**Pull request by apupier**
provided as a JSON list following the Camel Catalog syntax.

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

# Pull Request informations

## Rebase & Merge default requirements

1. Green build for master branch
2. Wait 24 hours after PR creation
3. Green job for PR
4. Approved PR

## PR labels default process

- READY_FOR_REVIEW  &rightarrow;  REVIEW_DONE  &rightarrow;  READY_FOR_MERGE

## Tests

- [ ] Are there **Unit tests**?
- [ ] Are there **Integration tests**?
- [ ] Do we need a new **UI test**?

## PR workflow progress

1. [ ] Tagged with relevant **PR labels**
2. [ ] Green **job for PR**
3. [ ] PR was created more than **24 hours ago** or **All committers approved** it
4. [ ] Green **master** branch build

### CODE REVIEW

**Comment by apupier** [comment]
demo video https://drive.google.com/file/d/1QnXlh4UkTclkg1w-YLt4gGPCM7qzToxE/view?usp=sharing

**Comment by lhein** [comment]
do we really need that full json blob? Can't we do it by specifying additional jars for instance?

**Comment by apupier** [comment]
> do we really need that full json blob?

It is the easiest to implement and most flexible solution that can cover all cases.

> Can't we do it by specifying additional jars for instance?

it is possible but it requires more work. Next iterations can be:
- point to a list of json files
- point to a jar containing the json file
- provide a maven groupid:artifactid:version
- read in the dependencies of the project to grab the additional artefacts

**Comment by lhein** [comment]
would it be possible to not be forced to open up the settings json file in an editor but to insert that blob via the preferences ui instead?

**Comment by lhein** [comment]
`"type": "array",
 "default": null,
 "items": {
    "type": "string"
 }`
?

**Comment by apupier** [comment]
> would it be possible to not be forced to open up the settings json file in an editor but to insert that blob via the preferences ui instead?

I have not found how to do it with VS Code API.
The advantage of the settings json editor is that it isa JSOn editor and that the parameter is a JSON objects, so benefiting from validation.

**Comment by apupier** [comment]
> `"type": "array", "default": null, "items": { "type": "string" }`
> ?

they are JSON Objects, not strings. I don't think we have a JSon schema for the Camel Catalog :-(

**Comment by lhein** [comment]
You are parsing a json string atm too. I don't see why that would be different.

**Comment by apupier** [comment]
with just "string", the UI is even less readable:

Screenshot from 2019-12-02 16-22-46
Screenshot from 2019-12-02 16-24-18

we are missing the JSon syntax validation in the settings.json:

Screenshot from 2019-12-02 16-24-56

**Comment by lhein** [comment]
ok, so lets improve that over time with better options.

**Pull request merged**
