### PR TITLE
FUSETOOLS2-1138 - added type information for kamelet parameters

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by lhein** [comment]
based on #611 to provide a more complete test experience (have both hover / description + the type information) available

**Comment by apupier** [comment]
builds are failing. Removing "ready for review" label

**Review by apupier — CHANGES_REQUESTED** [review]
missign test

**Comment by lhein** [comment]
It is already indirectly tested by KameletCompletionTest.

**Comment by lhein** [comment]
added another test

**Review by apupier — APPROVED** [review]

**Pull request merged**
