### PR TITLE
making the diagnostics computation async #116

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

### CODE REVIEW

**Comment by apupier** [comment]
@lhein any reasons preventing the merge of this PR?

**Comment by lhein** [comment]
yeah, I have still not tested with big to huge camel files.

**Comment by lhein** [comment]
tested now with a ~1250 lines camel context file and diagnostics takes a little more than a second. So I guess we are safe to also enable it for each text edit and not only on save time. @apupier

**Comment by lhein** [comment]
created https://github.com/camel-tooling/camel-language-server/issues/173

**Pull request merged**
